# https://docs.travis-ci.com/user/languages/java/
language: java
jdk: openjdk8

#https://dzone.com/articles/travis-ci-tutorial-java-projects
cache:
  directories:
  - $HOME/.m2

# используем режим обычного пользователя для сборки проекта.
sudo: false

dist: xenial

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# https://docs.travis-ci.com/user/customizing-the-build#Building-Specific-Branches
branches:
  only:
  - master

# Отправлять уведомление на почту если сборка упала
notifications:
  email:
    recipients:
      - aglizin@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always
© 2019 GitHub, Inc.